config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create, :index]
  end
  resources :reviews, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def show
  end

  def index
    @review = Review.all

  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to("#{restaurant.name}", restaurant_path(restaurant.id)) %></li>
  <% end %>
</ul>

<%= link_to "Create a new restaurant", new_restaurant_path, class: "btn btn-primary"%>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<div class="container">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
  <hr>
<%= link_to "Cancel", restaurants_path, class: "btn btn-primary" %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
<%= link_to "see reviews", restaurant_reviews_path(@restaurant), class: "btn btn-primary" %>

<%= link_to "Back to the list", restaurants_path, class: "btn btn-primary" %>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/reviews/index.html.erb
<ul>
  <%= @review.each do |r| %>
    <li><%= r.content %></li>
</ul>
<% end %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<div class="container">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>
  <hr>
<%= link_to "Cancel", restaurants_path, class: "btn btn-primary" %>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

<p><%= @review %></p>